# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  scenariomobilesrv:
    image: scenariomobilesrv
    build:
      context: .
      dockerfile: Scenario.MobileSrv/Dockerfile
    ports:
      - 5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - scenarioauthsrv
  scenarioauthsrv:
    image: scenarioauthsrv
    build:
      context: .
      dockerfile: Scenario.AuthSrv/Dockerfile
    ports:
      - 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
