# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  mobileAPI:
    image: scenariomobilesrv
    build:
      context: .
      dockerfile: Scenario.MobileSrv/Dockerfile
    ports:
      - 80
    depends_on:
      - auth
  auth:
    image: scenarioauthsrv
    build:
      context: .
      dockerfile: Scenario.AuthSrv/Dockerfile
    ports:
      - 80
    environment:
      - MOBILE_URL=http://mobileAPI:80